Add Applicant class
AY2223S2-CS2103T-W14-3/tp pull request #22
Opened 2023-03-01 12:05 UTC by homuntan02

## Which ticket does this address

- closes #13 

## What problems does this solve

- Add Applicant class

## Solution/Changes

- Added applicant package which contains applicant classes

## Checklist

- [ ] All tests pass locally and on CI

2023-03-02 01:08 UTC, yyj-02 requested changes
Please add more test cases to pass codecov

2023-03-05 08:04 UTC, yyj-02 commented on src/main/java/seedu/address/model/applicant/Applicant.java
> +    // Identity fields
I don't think we need to explain what type of field it is in the future

2023-03-05 14:44 UTC, clevon-w requested changes

2023-03-05 14:44 UTC, clevon-w commented on src/test/java/seedu/address/model/applicant/ApplicantTest.java
> +    public void isSamePerson() {
Should we change this to `isSameApplicant` instead? Since Person is gonna be deleted and `Person` is also not related to `Applicant`

2023-03-05 14:44 UTC, clevon-w commented on src/main/java/seedu/address/model/applicant/Applicant.java
> + * Represents an Applicant in the address book.
in a `Listing` right?

2023-03-05 14:44 UTC, clevon-w commented on src/main/java/seedu/address/model/applicant/Name.java
> + * Represents an Applicant's name in the address book.
same here, should be `in a Listing` and not address book right?

2023-03-05 15:00 UTC, clevon-w approved these changes
Alls good

2023-03-06 07:10 UTC, yyj-02 requested changes

2023-03-06 07:20 UTC, yyj-02 approved these changes
lgtm

2023-03-06 07:22 UTC, merged