66-sort-listings
AY2223S2-CS2103T-W14-3/tp pull request #87
Opened 2023-03-21 15:17 UTC by yyj-02

## Which ticket does this address

- closes #66

## What problems does this solve

- Users can now sort the listings

## Solution/Changes

- Add relevant test, command, parser and one new prefix

## Checklist

- [x] All tests pass locally and on CI

2023-03-22 05:16 UTC, homuntan02 requested changes

2023-03-22 18:40 UTC, panpannnnn approved these changes
lgtm

2023-03-22 18:40 UTC, panpannnnn commented on src/main/java/seedu/address/logic/Logic.java
> +    /** Returns an unmodifiable view of the list of listing to be displayed */
good call changing the name

2023-03-23 07:41 UTC, homuntan02 approved these changes
Looks good!

2023-03-23 07:41 UTC, merged